FROM alpine:latest

RUN apk add --no-cache bash git
RUN apk add --no-cache autoconf automake make binutils cmake ninja readline-dev libtool
RUN apk add --no-cache clang clang-dev lld musl-dev gcc g++
RUN apk add --no-cache llvm compiler-rt compiler-rt-static libunwind linux-headers

