if(APPLE)
    set(OPENSSL_ROOT_DIR /usr/local/opt/openssl@1.1/)
    set(OPENSSL_INCLUDE_DIR /usr/local/opt/openssl@1.1/include)
    list(APPEND OPENSSL_LIBRARIES ssl crypto)
else()
    set(OPENSSL_ROOT_DIR /usr/lib/)
    find_package(OpenSSL)
endif()

if (ENABLE_STATIC_BUILD)
    set(OPENSSL_ROOT_DIR ${EXTERNAL_PROJECTS_DIR})
    set(OPENSSL_INCLUDE_DIR ${EXTERNAL_PROJECTS_INCLUDE_DIR})
    set(OPENSSL_LIBRARIES ssl crypto)
endif()

include_directories(${EXTERNAL_PROJECTS_INCLUDE_DIR} ${OPENSSL_INCLUDE_DIR})
link_directories(${EXTERNAL_PROJECTS_LIB_DIR} ${OPENSSL_ROOT_DIR}/lib)
